### ISSUE TITLE
NPM version 5 removes dependencies

### ISSUE THREAD

**Issue by geraintwhite** [semantic-release/cracks#9]
In npm 5 that comes bundled with node 8 (I have npm v5.4.1 and node v8.4.0), dependencies are removed when npm install is run:
```
geraintwhite@Geraint-Mac ~/repos/node/github-listener (master +=) $ npm install
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated conventional-changelog@0.0.17: Please update conventional-changelog to >1.0.0. If you are running the cli, use conventional-changelog-cli
added 34 packages, removed 109 packages and updated 7 packages in 7.786s
```

The issue this causes with cracks is that the dependencies object is removed from the package.json in order to just install devDependencies, resulting in npm 5 actually removing the non devDependencies from node_modules. Perhaps a better solution is to run `npm install --only=dev` to just install the devDependencies?

**Comment by pvdlg** [comment]
Close in favor of #12
